title:            zpnk.me
tagline:          words and stuff.
description:      zpnk's blog.

#url: http://zpnk.me

owner:
  name:           Zach
  #avatar:         avatar.png
  bio:            "Learning &amp; Building"
  email:          z@zpnk.me
  twitter:        zpnk     
  github:         zpnk     
  instagram:      zkeg     
  dribbble:       zpnk

links:
  - title: Blog
    url: /blog


timezone:    America/Los_Angeles
future:      true
pygments:    true
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

coderay:
  coderay_line_numbers: 
  coderay_line_numbers_start: 1
  coderay_tab_width: 4
  coderay_bold_every: 10
  coderay_css: class

permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]